const translations = {
  en: {
    pageTitle: "Choose Your GOAT",
    metaDescription: "Compare football greats at the same age, career stage, or number of appearances.",
    homeAria: "Choose Your GOAT home", navAria: "Main navigation", compare: "Compare", method: "Method", coverage: "Coverage",
    eyebrow: "FIFTEEN PLAYERS · ONE COMMON SCALE", heroTitle: "Greatness needs<br><em>a denominator.</em>", heroText: "Compare football's defining attackers at the same age, career stage, or number of appearances—not just at retirement.", heroCta: "Build a comparison",
    releaseTitle: "Sourced research release · cutoff 31 December 2025", releaseText: "Timeline curves use dated or season-allocated records. Undated multi-year aggregates remain documented but are not assigned to an arbitrary endpoint.",
    matchupKicker: "01 / THE MATCH-UP", pickLegends: "Pick your legends", pickText: "Select any number of players (minimum two), or compare the entire field. Every headline value is evaluated at the last point all selected players have in common.",
    searchPlayers: "Search players", searchPlaceholder: "Name or country", era: "Era", allEras: "All eras", before1980: "Before 1980", modernEra: "1980–2009", currentEra: "2010–present", role: "Role", allRoles: "All roles", forward: "Forward", attackingMidfielder: "Attacking midfielder", country: "Country", allCountries: "All countries", playerSelectionAria: "Player selection",
    includeChart: "INCLUDE IN THE CHART", chooseGoals: "Choose which goals count", filterPresetsAria: "Filter presets", allCategories: "All categories", clubOnly: "Club only", nationalOnly: "National team only",
    measure: "Measure", cumulativeGoals: "Cumulative goals", cumulativeGoalsPerGame: "Cumulative average goals / game", marginalGoalsPerGame: "Marginal average goals / game", normalizeBy: "Normalize by", age: "Age", appearances: "Appearances", careerSeason: "Career season", commonOnly: "Common support only",
    byAge: "By age", chartAria: "Interactive comparison chart", hoverDetail: "Hover or focus a point for detail", rateExplanation: "Rate curves can be normalized by age or cumulative appearances. Marginal averages use the matches in each dated season/calendar-year observation; cumulative averages use every selected match through that point.",
    competitionKicker: "02 / COMPETITION RECORD", competitionHeading: "Winning the competitions entered", competitionText: "An edition counts only when participation is documented by an appearance or bench listing. Friendlies are excluded. This chart has its own competition-family choices.",
    includeCompetitionChart: "INCLUDE IN THE COMPETITION CHART", chooseCompetitions: "Choose which competitions count", competitionPresetsAria: "Competition filter presets", competitionMeasure: "Competition measure", cumulativeCompetitionsWon: "Cumulative competitions won", cumulativeWinRate: "Cumulative average win rate", competitionsPlayed: "Competitions played", byCompetitionsPlayed: "By competitions played", competitionChartAria: "Interactive competition comparison chart", appearanceCoverage: "Appearance-confirmed edition coverage",
    rulesKicker: "02 / THE RULES", rulesTitle: "Same question.<br>Same exposure.", commonSupport: "Common support", commonSupportText: "Career comparisons stop at the latest age or appearance count observed for every selected player.", chooseUniverse: "You choose the universe", chooseUniverseText: "Named competition families stay separate. No source-defined status decides which matches count.", visibleSources: "Sources stay visible", visibleSourcesText: "National-team points come from complete match ledgers. Historical club points use season-by-competition aggregates and are labelled accordingly.",
    coverageKicker: "03 / DATA COVERAGE", coverageTitle: "Trust the gaps, too.", coverageText: "Coverage is stated by field and granularity. Aggregate rows are never silently added to overlapping match-level records.", player: "Player", clubRecord: "Club record", seniorNational: "Senior national team", titles: "Titles", status: "Status", sourced: "Sourced",
    footerText: "Evidence first. Arguments welcome.", methodology: "Methodology ↗",
    selected: "selected", selectAll: "Select all {count}", reset: "Reset", noPlayers: "No players match these filters.", categoriesIncluded: "{count} categories included: {labels}", noCategories: "No categories selected. Choose at least one category to draw the chart.", competitionCategoriesIncluded: "{count} competition categories included: {labels}", noCompetitionCategories: "No competition categories selected.",
    noObservations: "No observations match these restrictions.", selectPopulated: "Select at least one populated category", noEditions: "No competition editions match these restrictions.", commonEndpoint: "Common endpoint: {value} {axis}", fullCareers: "Full available careers · data cutoff {cutoff}", fullEditions: "Full available edition coverage · cutoff {cutoff}", byAxis: "By {axis}",
    year: "Year", goals: "goals", games: "games", won: "won", played: "played", cumulative: "cumulative", inPeriod: "in period", selectedEditions: "selected championship editions",
    reconciliationPartial: "reconciliation partial", honoursAdjudicated: "all honours adjudicated · {count} excluded for no participation evidence", honoursMatchedUnnamed: "all honours matched · {count} unnamed source row excluded", honoursMatched: "all reported honours matched",
    clubGoals: "Club goals", nationalTeamGoals: "National-team goals", clubCompetitions: "Club competitions", nationalTeamCompetitions: "National-team competitions",
    national_league: "National league", lower_division_club: "Lower-division clubs", continental_federation_cup: "Continental federation cup", intercontinental_federation_cup: "Intercontinental federation cup", regional_league: "Regional league", all_other_club: "All other club goals",
    national_team_world_cup_finals: "World Cup finals", national_team_world_cup_qualification: "World Cup qualification", national_team_continental_championship_finals: "Continental championship finals", national_team_continental_championship_qualification: "Continental championship qualification", national_team_intercontinental_championship_finals: "Intercontinental championship finals", national_team_continental_nations_league: "Continental Nations League", national_team_olympic: "Olympic", national_team_youth: "Youth national teams", national_team_friendlies: "Friendlies", national_team_other: "All other national-team goals"
  },
  es: {
    pageTitle: "Elige tu GOAT", metaDescription: "Compara a las leyendas del fútbol a la misma edad, etapa de carrera o número de partidos.", homeAria: "Inicio de Elige tu GOAT", navAria: "Navegación principal", compare: "Comparar", method: "Método", coverage: "Cobertura",
    eyebrow: "QUINCE JUGADORES · UNA ESCALA COMÚN", heroTitle: "La grandeza necesita<br><em>un denominador.</em>", heroText: "Compara a los atacantes que definieron el fútbol a la misma edad, etapa de carrera o número de partidos, no solo al retirarse.", heroCta: "Crear una comparación",
    releaseTitle: "Publicación de investigación con fuentes · corte: 31 de diciembre de 2025", releaseText: "Las curvas usan registros fechados o asignados por temporada. Los agregados plurianuales sin fecha quedan documentados, pero no se asignan a un punto final arbitrario.",
    matchupKicker: "01 / EL DUELO", pickLegends: "Elige tus leyendas", pickText: "Selecciona cualquier número de jugadores (mínimo dos) o compara a todos. Cada valor principal se evalúa en el último punto común a todos los seleccionados.",
    searchPlayers: "Buscar jugadores", searchPlaceholder: "Nombre o país", era: "Época", allEras: "Todas las épocas", before1980: "Antes de 1980", modernEra: "1980–2009", currentEra: "2010–presente", role: "Posición", allRoles: "Todas", forward: "Delantero", attackingMidfielder: "Mediapunta", country: "País", allCountries: "Todos los países", playerSelectionAria: "Selección de jugadores",
    includeChart: "INCLUIR EN EL GRÁFICO", chooseGoals: "Elige qué goles cuentan", filterPresetsAria: "Filtros predefinidos", allCategories: "Todas las categorías", clubOnly: "Solo clubes", nationalOnly: "Solo selección",
    measure: "Medida", cumulativeGoals: "Goles acumulados", cumulativeGoalsPerGame: "Promedio acumulado de goles por partido", marginalGoalsPerGame: "Promedio marginal de goles por partido", normalizeBy: "Normalizar por", age: "Edad", appearances: "Partidos", careerSeason: "Temporada de carrera", commonOnly: "Solo soporte común",
    byAge: "Por edad", chartAria: "Gráfico interactivo de comparación", hoverDetail: "Pasa el cursor o enfoca un punto para ver detalles", rateExplanation: "Las tasas pueden normalizarse por edad o partidos acumulados. Los promedios marginales usan los partidos de cada temporada o año; los acumulados usan todos los partidos seleccionados hasta ese punto.",
    competitionKicker: "02 / HISTORIAL DE COMPETICIONES", competitionHeading: "Ganar las competiciones disputadas", competitionText: "Una edición cuenta solo con participación documentada mediante aparición o presencia en el banquillo. Se excluyen los amistosos. Este gráfico tiene sus propios filtros.",
    includeCompetitionChart: "INCLUIR EN EL GRÁFICO DE COMPETICIONES", chooseCompetitions: "Elige qué competiciones cuentan", competitionPresetsAria: "Filtros de competiciones", competitionMeasure: "Medida de competición", cumulativeCompetitionsWon: "Competiciones ganadas acumuladas", cumulativeWinRate: "Promedio acumulado de victorias", competitionsPlayed: "Competiciones disputadas", byCompetitionsPlayed: "Por competiciones disputadas", competitionChartAria: "Gráfico interactivo de competiciones", appearanceCoverage: "Cobertura de ediciones con participación confirmada",
    rulesKicker: "02 / LAS REGLAS", rulesTitle: "Misma pregunta.<br>Misma exposición.", commonSupport: "Soporte común", commonSupportText: "Las comparaciones terminan en la última edad o cantidad de partidos observada para todos los jugadores seleccionados.", chooseUniverse: "Tú eliges el universo", chooseUniverseText: "Las familias de competiciones permanecen separadas. Ningún estatus definido por una fuente decide qué partidos cuentan.", visibleSources: "Fuentes visibles", visibleSourcesText: "Los puntos de selección vienen de registros completos. Los datos históricos de clubes usan agregados por temporada y competición, debidamente identificados.",
    coverageKicker: "03 / COBERTURA DE DATOS", coverageTitle: "Confía también en los vacíos.", coverageText: "La cobertura se declara por campo y granularidad. Los agregados nunca se suman silenciosamente a registros solapados por partido.", player: "Jugador", clubRecord: "Registro de clubes", seniorNational: "Selección absoluta", titles: "Títulos", status: "Estado", sourced: "Con fuentes",
    footerText: "Primero la evidencia. Bienvenido el debate.", methodology: "Metodología ↗",
    selected: "seleccionados", selectAll: "Seleccionar los {count}", reset: "Restablecer", noPlayers: "Ningún jugador coincide con estos filtros.", categoriesIncluded: "{count} categorías incluidas: {labels}", noCategories: "No hay categorías seleccionadas. Elige al menos una para dibujar el gráfico.", competitionCategoriesIncluded: "{count} categorías de competición incluidas: {labels}", noCompetitionCategories: "No hay categorías de competición seleccionadas.",
    noObservations: "Ninguna observación coincide con estas restricciones.", selectPopulated: "Selecciona al menos una categoría con datos", noEditions: "Ninguna edición coincide con estas restricciones.", commonEndpoint: "Punto final común: {value} {axis}", fullCareers: "Carreras completas disponibles · corte {cutoff}", fullEditions: "Cobertura completa de ediciones disponible · corte {cutoff}", byAxis: "Por {axis}",
    year: "Año", goals: "goles", games: "partidos", won: "ganadas", played: "disputadas", cumulative: "acumulado", inPeriod: "en el período", selectedEditions: "ediciones de campeonato seleccionadas",
    reconciliationPartial: "conciliación parcial", honoursAdjudicated: "todos los honores revisados · {count} excluidos por falta de evidencia de participación", honoursMatchedUnnamed: "todos los honores vinculados · {count} fila sin nombre excluida", honoursMatched: "todos los honores declarados vinculados",
    clubGoals: "Goles de clubes", nationalTeamGoals: "Goles de selección", clubCompetitions: "Competiciones de clubes", nationalTeamCompetitions: "Competiciones de selección",
    national_league: "Liga nacional", lower_division_club: "Clubes de divisiones inferiores", continental_federation_cup: "Copa continental de federación", intercontinental_federation_cup: "Copa intercontinental de federación", regional_league: "Liga regional", all_other_club: "Otros goles de clubes",
    national_team_world_cup_finals: "Fase final del Mundial", national_team_world_cup_qualification: "Eliminatorias del Mundial", national_team_continental_championship_finals: "Fase final continental", national_team_continental_championship_qualification: "Clasificación continental", national_team_intercontinental_championship_finals: "Finales de campeonatos intercontinentales", national_team_continental_nations_league: "Liga de Naciones continental", national_team_olympic: "Juegos Olímpicos", national_team_youth: "Selecciones juveniles", national_team_friendlies: "Amistosos", national_team_other: "Otros goles de selección"
  },
  pt: {
    pageTitle: "Escolha o seu GOAT", metaDescription: "Compare craques do futebol na mesma idade, fase da carreira ou número de jogos.", homeAria: "Início do Escolha o seu GOAT", navAria: "Navegação principal", compare: "Comparar", method: "Método", coverage: "Cobertura",
    eyebrow: "QUINZE JOGADORES · UMA ESCALA COMUM", heroTitle: "A grandeza precisa<br><em>de um denominador.</em>", heroText: "Compare os atacantes que definiram o futebol na mesma idade, fase da carreira ou número de jogos — não apenas na aposentadoria.", heroCta: "Montar uma comparação",
    releaseTitle: "Pesquisa documentada · corte em 31 de dezembro de 2025", releaseText: "As curvas usam registros datados ou alocados por temporada. Agregados plurianuais sem data continuam documentados, mas não são atribuídos a um ponto final arbitrário.",
    matchupKicker: "01 / O CONFRONTO", pickLegends: "Escolha suas lendas", pickText: "Selecione quantos jogadores quiser (mínimo de dois) ou compare todos. Cada valor principal é avaliado no último ponto comum a todos os selecionados.",
    searchPlayers: "Buscar jogadores", searchPlaceholder: "Nome ou país", era: "Era", allEras: "Todas as eras", before1980: "Antes de 1980", modernEra: "1980–2009", currentEra: "2010–presente", role: "Posição", allRoles: "Todas", forward: "Atacante", attackingMidfielder: "Meia-atacante", country: "País", allCountries: "Todos os países", playerSelectionAria: "Seleção de jogadores",
    includeChart: "INCLUIR NO GRÁFICO", chooseGoals: "Escolha quais gols contam", filterPresetsAria: "Filtros predefinidos", allCategories: "Todas as categorias", clubOnly: "Somente clubes", nationalOnly: "Somente seleção",
    measure: "Medida", cumulativeGoals: "Gols acumulados", cumulativeGoalsPerGame: "Média acumulada de gols por jogo", marginalGoalsPerGame: "Média marginal de gols por jogo", normalizeBy: "Normalizar por", age: "Idade", appearances: "Jogos", careerSeason: "Temporada da carreira", commonOnly: "Somente suporte comum",
    byAge: "Por idade", chartAria: "Gráfico comparativo interativo", hoverDetail: "Passe o cursor ou foque em um ponto para ver detalhes", rateExplanation: "As taxas podem ser normalizadas por idade ou jogos acumulados. As médias marginais usam os jogos de cada temporada ou ano; as acumuladas usam todos os jogos selecionados até aquele ponto.",
    competitionKicker: "02 / HISTÓRICO DE COMPETIÇÕES", competitionHeading: "Vencer as competições disputadas", competitionText: "Uma edição só conta com participação documentada por atuação ou presença no banco. Amistosos são excluídos. Este gráfico tem seus próprios filtros.",
    includeCompetitionChart: "INCLUIR NO GRÁFICO DE COMPETIÇÕES", chooseCompetitions: "Escolha quais competições contam", competitionPresetsAria: "Filtros de competições", competitionMeasure: "Medida de competição", cumulativeCompetitionsWon: "Competições vencidas acumuladas", cumulativeWinRate: "Média acumulada de vitórias", competitionsPlayed: "Competições disputadas", byCompetitionsPlayed: "Por competições disputadas", competitionChartAria: "Gráfico comparativo de competições", appearanceCoverage: "Cobertura de edições com participação confirmada",
    rulesKicker: "02 / AS REGRAS", rulesTitle: "Mesma pergunta.<br>Mesma exposição.", commonSupport: "Suporte comum", commonSupportText: "As comparações terminam na última idade ou número de jogos observado para todos os jogadores selecionados.", chooseUniverse: "Você escolhe o universo", chooseUniverseText: "As famílias de competições permanecem separadas. Nenhum status definido por uma fonte decide quais partidas contam.", visibleSources: "Fontes visíveis", visibleSourcesText: "Os pontos de seleção vêm de registros completos. Os dados históricos de clubes usam agregados por temporada e competição, devidamente identificados.",
    coverageKicker: "03 / COBERTURA DOS DADOS", coverageTitle: "Confie também nas lacunas.", coverageText: "A cobertura é declarada por campo e granularidade. Agregados nunca são somados silenciosamente a registros sobrepostos por partida.", player: "Jogador", clubRecord: "Registro por clubes", seniorNational: "Seleção principal", titles: "Títulos", status: "Status", sourced: "Com fontes",
    footerText: "Evidência primeiro. Debate bem-vindo.", methodology: "Metodologia ↗",
    selected: "selecionados", selectAll: "Selecionar todos os {count}", reset: "Redefinir", noPlayers: "Nenhum jogador corresponde a estes filtros.", categoriesIncluded: "{count} categorias incluídas: {labels}", noCategories: "Nenhuma categoria selecionada. Escolha pelo menos uma para desenhar o gráfico.", competitionCategoriesIncluded: "{count} categorias de competição incluídas: {labels}", noCompetitionCategories: "Nenhuma categoria de competição selecionada.",
    noObservations: "Nenhuma observação corresponde a estas restrições.", selectPopulated: "Selecione pelo menos uma categoria com dados", noEditions: "Nenhuma edição corresponde a estas restrições.", commonEndpoint: "Ponto final comum: {value} {axis}", fullCareers: "Carreiras completas disponíveis · corte {cutoff}", fullEditions: "Cobertura completa de edições disponível · corte {cutoff}", byAxis: "Por {axis}",
    year: "Ano", goals: "gols", games: "jogos", won: "vencidas", played: "disputadas", cumulative: "acumulado", inPeriod: "no período", selectedEditions: "edições de campeonato selecionadas",
    reconciliationPartial: "conciliação parcial", honoursAdjudicated: "todas as honrarias revisadas · {count} excluídas por falta de evidência de participação", honoursMatchedUnnamed: "todas as honrarias vinculadas · {count} linha sem nome excluída", honoursMatched: "todas as honrarias declaradas vinculadas",
    clubGoals: "Gols por clubes", nationalTeamGoals: "Gols pela seleção", clubCompetitions: "Competições de clubes", nationalTeamCompetitions: "Competições de seleção",
    national_league: "Liga nacional", lower_division_club: "Clubes de divisões inferiores", continental_federation_cup: "Copa continental de federação", intercontinental_federation_cup: "Copa intercontinental de federação", regional_league: "Liga regional", all_other_club: "Outros gols por clubes",
    national_team_world_cup_finals: "Fase final da Copa do Mundo", national_team_world_cup_qualification: "Eliminatórias da Copa do Mundo", national_team_continental_championship_finals: "Fase final continental", national_team_continental_championship_qualification: "Eliminatórias continentais", national_team_intercontinental_championship_finals: "Finais de campeonatos intercontinentais", national_team_continental_nations_league: "Liga das Nações continental", national_team_olympic: "Olímpico", national_team_youth: "Seleções de base", national_team_friendlies: "Amistosos", national_team_other: "Outros gols pela seleção"
  }
};

const countryTranslations = {
  es: { Argentina: "Argentina", Brazil: "Brasil", France: "Francia", Germany: "Alemania", Hungary: "Hungría", Netherlands: "Países Bajos", Norway: "Noruega", Poland: "Polonia", Portugal: "Portugal" },
  pt: { Argentina: "Argentina", Brazil: "Brasil", France: "França", Germany: "Alemanha", Hungary: "Hungria", Netherlands: "Países Baixos", Norway: "Noruega", Poland: "Polônia", Portugal: "Portugal" }
};

export const supportedLanguages = ["en", "es", "pt"];
export const localeFor = language => ({ en: "en-GB", es: "es-ES", pt: "pt-BR" }[language] || "en-GB");
export const getInitialLanguage = () => {
  const saved = localStorage.getItem("chooseyourgoat-language");
  return supportedLanguages.includes(saved) ? saved : "en";
};
export const saveLanguage = language => localStorage.setItem("chooseyourgoat-language", language);
export const translate = (language, key, values = {}) => {
  let value = translations[language]?.[key] ?? translations.en[key] ?? key;
  for (const [name, replacement] of Object.entries(values)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
};
export const translateCountry = (language, country) => countryTranslations[language]?.[country] || country;
export const taxonomyLabel = (language, id, competition = false) => {
  if (id === "club") return translate(language, competition ? "clubCompetitions" : "clubGoals");
  if (id === "national_team") return translate(language, competition ? "nationalTeamCompetitions" : "nationalTeamGoals");
  const label = translate(language, id);
  if (!competition) return label;
  return label.replace(/ goals$| goles$| gols$/i, "");
};
